apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: capgeminisreeastusacr.azurecr.io/spring-petclinic-api-gateway
          name: api-gateway
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              memory: 100M
          envFrom:
            - configMapRef:
                name: petclinic-configmap
      hostNetwork: false  
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey