apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: grafana-server
    spec:
      containers:
        - image: capgeminisreeastusacr.azurecr.io/spring-petclinic-grafana-server
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://grafana-server:3000
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 3
          name: grafana-server
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              memory: 100M
          envFrom:
            - configMapRef:
                name: petclinic-configmap
      hostNetwork: false       
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey