apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    io.kompose.service: api-gateway
  ports:
    - name: 'petclinic-service'
    - port: 80
      targetPort: 8080

  type: LoadBalancer