apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: visits-service
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: visits-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/spring-petclinic-microservices-default: "true"
        io.kompose.service: visits-service
    spec:
      containers:
        - image: capgeminisreeastusacr.azurecr.io/spring-petclinic-visits-service
          name: visits-service
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: 512M
          envFrom:
            - configMapRef:
                name: petclinic-configmap
      hostNetwork: false        
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
